name: Check step 3, Release pull request opened

# This step triggers after 2-feature-added-to-release.yml
# This step sets STEP to 4
# This step closes <details id=3> and opens <details id=4>

# This will run every time a pull request is opened to main
# Reference https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  pull_request:
    types: [opened]
    branches: [main]

permissions:
  contents: write

jobs:
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: get_step
        run: |
          echo '::echo::on'
          echo "::set-output name=current_step::$(cat ./.github/script/STEP)"
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_release_pr_opened:
    name: On release pull request opened
    needs: get_current_step

    # We will only run this action when:
    # 1. This repository isn't the template repository
    # 1. The STEP is currently '3'
    # 1. The pull request head branch is 'release-v1.0'
    # Reference https://docs.github.com/en/actions/learn-github-actions/contexts
    # Reference https://docs.github.com/en/actions/learn-github-actions/expressions
    if: ${{ !github.event.repository.is_template && needs.get_current_step.outputs.current_step == 3 && github.head_ref == 'release-v1.0' }}

    # We'll run Ubuntu for performance instead of Mac or Windows
    runs-on: ubuntu-latest

    steps:
      # We'll need to check out the repository so that we can edit the README
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Update README to close <details id=3>
      # and open <details id=4>
      # and set STEP to '4'
      - name: Update to step 4
        uses: skills/action-update-step@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 3
          to_step: 4
  