name: Check step 5, Commit hotfix

# This step triggers after 4-release-notes-and-merge.yml
# This step sets STEP to 6
# This step closes <details id=1> and opens <details id=2>

# This will run when a release is published
# Reference https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  release:
    types: [published]

# Reference https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  contents: write
  pull-requests: write

jobs:
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: get_step
        run: |
          echo '::echo::on'
          echo "::set-output name=current_step::$(cat ./.github/script/STEP)"
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_release_published:
    name: On release v1.0 published
    needs: get_current_step

    # We will only run this action when:
    # 1. This repository isn't the template repository
    # 1. The STEP is currently '5'
    # 1. The tag for the published release is v1.0.0
    # Reference https://docs.github.com/en/actions/learn-github-actions/contexts
    # Reference https://docs.github.com/en/actions/learn-github-actions/expressions
    if: ${{ !github.event.repository.is_template && needs.get_current_step.outputs.current_step == 5 && github.ref_name == 'v1.0.0' }}

    # We'll run Ubuntu for performance instead of Mac or Windows
    runs-on: ubuntu-latest

    steps:
      # We'll need to check out the repository so that we can edit the README
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      # Create a release-v1.0.1 hotfix branch
      - name: Create hotfix branch
        run: ./.github/script/create-hotfix-pr.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Update README to close <details id=5>
      # and open <details id=6>
      # and set STEP to '6'
      - name: Update to step 6
        uses: skills/action-update-step@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 5
          to_step: 6
  
